version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    networks:
      - yii2
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    networks:
      - yii2
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

networks:
  yii2:
    driver: bridge

volumes:
  database:
    driver: local
